version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8001:8000
    depends_on:
      - main_db 

    volumes:
      - ./:/app
    networks:
      - mm-network

  main_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      main_db:
        condition: service_healthy
        restart: true
    networks:
      - mm-network
    env_file:
      - .env


  main_db:
    image: mysql:5.7.22
    healthcheck:
      test: out=$$(mysqladmin ping -h main_db -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33071:3306
    networks:
      - mm-network  
networks:
  mm-network:
    external: true
